In [118]:
import numpy as np
from collections import deque

In [119]:
class NetworkProcessor3:
    def __init__(self, file_path):
      self.file_path = file_path # Read file
      self.lines_list = [] #line ,a b,d c
      #
      self.edges = [] # Split \n, \t
      self.nodes = []
      #
      self.network_array = []

    def read_file(self):
      with open(self.file_path, 'r') as file:
        line = file.readline()
        while line:
            self.lines_list.append(line)
            line = file.readline()

    def get_edges(self):
      edge = [item.strip('\n') for item in self.lines_list]
      self.edges = [item.split('\t') for item in edge]

    def get_unique_nodes(self):
      all_nodes = [item for sublist in self.edges for item in sublist]
      unique_nodes = list(set(all_nodes))
      self.nodes = sorted(unique_nodes)

    def get_in_or_out_degree(self):
      for node in self.nodes:
        in_degree = 0
        out_degree = 0
        for start_node,end_node in self.edges:
          if node == start_node:
            out_degree +=1
          if node == end_node:
            in_degree +=1
        print('{} in-degree = {}, out-degree = {}'.format(node, in_degree, out_degree))

    def get_network_array(self):
      self.network_array = np.zeros((len(self.nodes), len(self.nodes)), dtype=int)
      for start_node, end_node in self.edges:
        row = self.nodes.index(start_node)
        col = self.nodes.index(end_node)
        self.network_array[row, col] = 1
      print(self.network_array)

    def get_connection(self):
      n = len(self.nodes)
      visited = np.zeros((n, n), dtype=bool)
      def dfs(row, col): #找路徑就用dfs
        if row < 0 or col < 0 or row >= n or col >= n:
          return False
        if visited[row, col] or self.network_array[row, col] == 0:
          return False
        visited[row, col] = True
        if row == n - 1 and col == n - 1:
          return True
        # Explore all four possible directions
        return (dfs(row + 1, col) or dfs(row - 1, col) or dfs(row, col + 1) or dfs(row, col - 1))
      if dfs(0, 0):
        print("Strongly connected")
      else:
        print("Weakly connected")

    def get_distent(self, nodeA, nodeB):
      start_node = self.nodes.index(nodeA)
      end_node = self.nodes.index(nodeB)
      visited = np.full(len(self.nodes), False, dtype=bool)
      distance = np.full(len(self.nodes), np.inf, dtype=float)
      distance[start_node] = 0
      def bfs(start): #找最短路徑就用bfs
        queue = [start]
        while queue:
          current = queue.pop(0)
          current_distance = distance[current]
          for neighbor, connected in enumerate(self.network_array[current]):
            if connected and not visited[neighbor]:
              visited[neighbor] = True
              distance[neighbor] = min(distance[neighbor], current_distance + 1)
              queue.append(neighbor)
      bfs(start_node)
      if distance[end_node] < np.inf:
        print(f"Node {nodeA} and node {nodeB} distance = {int(distance[end_node])}")
      else:
        print(f"Node {nodeA} and node {nodeB} distance = na")

    def get_subgraph(self, node_count):
      final_subgraph = set()
      for i in range(len(self.nodes)):
        visited = [False] * len(self.nodes)
        queue = deque([i])
        visited[i] = True
        list_subgraph = []
        while queue:
          current_node = queue.popleft()
          list_subgraph.append(current_node)
          for neighbor in range(len(self.nodes)):
            if self.network_array[current_node][neighbor] == 1 and not visited[neighbor]:
              visited[neighbor] = True
              queue.append(neighbor)
          if len(list_subgraph) >= node_count:
            final_subgraph.add(tuple(sorted(list_subgraph)))
      if final_subgraph != []:
        print('Subgraphs containing at least ', node_count,' nodes:')
        for subgraph in final_subgraph:
          print([self.nodes[node] for node in subgraph])
      else:
        print('No subgraph containing at least ', node_count,' nodes found.')

### 1. calculate the in-degree sequence and out-degree sequence of them

In [120]:
#network
network = NetworkProcessor3('Network1.txt') #Network2.txt
network.read_file()
network.get_edges()
network.get_unique_nodes()
network.get_in_or_out_degree()

a in-degree = 0, out-degree = 1
b in-degree = 1, out-degree = 1
c in-degree = 2, out-degree = 0
d in-degree = 1, out-degree = 3
e in-degree = 2, out-degree = 4
f in-degree = 2, out-degree = 2
g in-degree = 2, out-degree = 2
h in-degree = 4, out-degree = 0
i in-degree = 0, out-degree = 1


### 2. check their connectivity, i.e. strongly or weakly connected

In [121]:
network.get_network_array()

[[0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0]
 [0 0 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 1 1 0]
 [0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]]


In [122]:
network.get_connection()

Weakly connected


### 3. calculate the distance between node a and node i

In [123]:
network.get_distent('a', 'g')

Node a and node g distance = na


### 4. list one subgraph containing at least 5 nodes for each network
• The listed subgraphs must be weakly connected

In [124]:
network.get_subgraph(5)

Subgraphs containing at least  5  nodes:
['c', 'e', 'f', 'g', 'h']
['d', 'e', 'f', 'g', 'h']
['c', 'e', 'f', 'g', 'h', 'i']
['c', 'd', 'e', 'f', 'g', 'h']
['c', 'e', 'f', 'g', 'i']
['c', 'd', 'e', 'f', 'h']
['c', 'd', 'e', 'f', 'g', 'h', 'i']
