In [ ]:
import numpy as np
from collections import deque

In [ ]:
class NetworkProcessor5:
    def __init__(self, file_path):
      self.file_path = file_path # Read file
      self.lines_list = [] #line ,a b,d c
      #
      self.edges = [] # Split \n, \t
      self.nodes = []
      #
      self.network_array = []
      #
      self.incidence_matrix = []
      #
      self.density = ''
      #
      self.transitive_closure = []

    def read_file(self):
      with open(self.file_path, 'r') as file:
        line = file.readline()
        while line:
            self.lines_list.append(line)
            line = file.readline()

    def get_edges(self):
      edge = [item.strip('\n') for item in self.lines_list]
      self.edges = [item.split('\t') for item in edge]

    def get_unique_nodes(self):
      all_nodes = [item for sublist in self.edges for item in sublist]
      unique_nodes = list(set(all_nodes))
      self.nodes = sorted(unique_nodes)

    def get_network_array(self):
      self.network_array = np.zeros((len(self.nodes), len(self.nodes)), dtype=int)
      for start_node, end_node in self.edges:
        row = self.nodes.index(start_node)
        col = self.nodes.index(end_node)
        self.network_array[row, col] = 1


    def get_incidence_matrix(self):
      num_nodes = len(self.nodes)
      start = []
      end = []
      for i in sorted(self.edges):
          node1,node2 =i
          start.append(node1)
          end.append(node2)
      edges = [(self.nodes.index(start[i]), self.nodes.index(end[i])) for i in range(len(start))]
      num_edges = len(edges)
      self.incidence_matrix = np.zeros((num_edges, num_nodes), dtype=int)
      for i, (start_node, end_node) in enumerate(edges):
          self.incidence_matrix[i, start_node] = 1
          self.incidence_matrix[i, end_node] = -1

    def get_density(self):
      num_nodes = self.network_array.shape[0]
      num_edges = np.sum(self.network_array)
      max_possible_edges = num_nodes * (num_nodes - 1)
      self.density = num_edges / max_possible_edges

    def get_transitive_closure(self):
        num_nodes = self.network_array.shape[0]
        self.transitive_closure = np.copy(self.network_array)
        for _ in range(num_nodes - 1):
            self.transitive_closure = np.maximum(self.transitive_closure, np.dot(self.transitive_closure, self.network_array))
        self.transitive_closure[self.transitive_closure != 0] = 1



###1. calculate its density


In [ ]:
#network
network = NetworkProcessor5('Network1')
network.read_file()
network.get_edges()
network.get_unique_nodes()
network.get_network_array()
network.get_incidence_matrix()
network.get_density()
print('Density = ',network.density)
network.get_transitive_closure()


Density =  0.19444444444444445


### 2. output its adjacency and incidence matrix & find its transitive closure


In [ ]:
print('Adjacency Network \n',network.network_array,'\n')

print('Incidence Matrix \n',network.incidence_matrix,'\n')

print('Transitive Closure \n',network.transitive_closure,'\n')

Adjacency Network 
 [[0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0]
 [0 0 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 1 1 0]
 [0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]] 

Incidence Matrix 
 [[ 1 -1  0  0  0  0  0  0  0]
 [ 0  1 -1  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0  0]
 [ 0  0  0  1  0 -1  0  0  0]
 [ 0  0  0  1  0  0  0 -1  0]
 [ 0  0 -1  0  1  0  0  0  0]
 [ 0  0  0  0  1 -1  0  0  0]
 [ 0  0  0  0  1  0 -1  0  0]
 [ 0  0  0  0  1  0  0 -1  0]
 [ 0  0  0  0  0  1 -1  0  0]
 [ 0  0  0  0  0  1  0 -1  0]
 [ 0  0  0 -1  0  0  1  0  0]
 [ 0  0  0  0  0  0  1 -1  0]
 [ 0  0  0  0 -1  0  0  0  1]] 

Transitive Closure 
 [[0 1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 0]
 [0 0 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 1 0]] 



###3. Propose the algorithms with pseudocode doing:
• run BFS with adjacency matrix structure \
• run DFS with adjacency list structure

In [ ]:
#pseudocode###
#run BFS with adjacency matrix structure
Function BFS(matrix, start_node):
    nodes = Length(matrix)  # Get the number of nodes in the graph
    visited = InitializeBooleanList(nodes, False)  # Initialize a boolean list to mark visited nodes
    start_index = IndexOf(unique_elements, start_node)  # Get the index of the start_node in unique_elements
    queue = CreateEmptyQueue()  # Initialize an empty queue for BFS traversal
    Enqueue(queue, (start_index, [start_node]))  # Enqueue the starting node and its path
    visited[start_index] = True  # Mark the starting node as visited
    final_path_BFS = InitializeEmptyList()  # Initialize a list to store final paths
    while queue is not empty:
        current_node, path = Dequeue(queue)  # Dequeue a node and its path from the queue
        For each neighbor in range(nodes):
            If undirected_matrix[current_node][neighbor] == 1 and not visited[neighbor]:
                # If there is an edge to an unvisited neighbor
                visited[neighbor] = True  # Mark the neighbor as visited
                Enqueue(queue, (neighbor, Concatenate(path, [unique_elements[neighbor]])))
                # Enqueue the neighbor with an extended path
        Append(final_path_BFS, path)  # Add the current path to the list of final paths
    Return final_path_BFS #all path of bfs

#run DFS with adjacency list structure
Function DFS_main(adjacency_list, start_node):
    Create a boolean list "visited" with the same length as adjacency_list and initialize it with "False" values
    Create an empty list "path" to store the traversal path
    Call the DFS function with parameters: adjacency_list, start_node, visited, path
    Return the "path" as the final result
Function DFS(adjacency_list, current_node, visited, path):
    visited[current_node] = True  # Mark the current node as visited
    Append current_node to the "path"
    For each neighbor in adjacency_list[current_node]:  # Iterate through neighbors
        If neighbor is not visited:
            Call DFS recursively with parameters: adjacency_list, neighbor, visited, path

SyntaxError: invalid syntax (<ipython-input-28-0438ee743b98>, line 3)